version: '3.7'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL = zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME = schema-registry
      - SCHEMA_REGISTRY_LISTENERS = http://schema-registry:8081, http://localhost:8081
    ports:
      - 8081:8081
    networks:
      - debkafsql_proxynet
  

  mysql:   
    image: quay.io/debezium/example-mysql:2.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD = debezium
      - MYSQL_USER = docker  
      - MYSQL_PASSWORD = debezium
    networks:
      - debkafsql_proxynet



networks:
  debkafsql_proxynet:
    external: true

