version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - proxynet
  

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka0
    ports:
      - 9094:9094
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - proxynet
  

  kafka_ui: 
    image: provectuslabs/kafka-ui:master
    container_name: kafka_ui0
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: localhost:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: stage
    networks:
      - proxynet
  



networks:
  proxynet:
    driver: bridge
  














      