version: '3.7'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1.arm64
    container_name: schema0
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka0:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081, http://localhost:8081
    ports:
      - 8081:8081
    networks:
      - debkafsql_proxynet


  mysql:   
    image: arm64v8/mysql
    container_name: mysql0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: docker  
      MYSQL_PASSWORD: debezium
      MYSQL_DATABASE: debezium
    networks:
      - debkafsql_proxynet


  kafkaconnect:
    image: quay.io/debezium/connect:2.1
    container_name: debezium
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka0:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://localhost:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://localhost:8081
    depends_on: [kafka]
    networks:
      - debkafsql_proxynet
  

networks:
  debkafsql_proxynet:
    external: true

