version: '3.7'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1.arm64
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka0:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081, http://localhost:8081
    ports:
      - 8081:8081
    networks:
      - debkafsql_proxynet


  

  mysql:   
    image: arm64v8/mysql
    container_name: mysql0
    ports:
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: docker  
      MYSQL_PASSWORD: debezium
    networks:
      - debkafsql_proxynet




networks:
  debkafsql_proxynet:
    external: true

